config = {}

config.itemList = {
	{ ['item'] = 'celular', ['damageItem'] = 'celular-queimado' },
	{ ['item'] = 'jbl', ['damageItem'] = 'jbl-queimada' },
	{ ['item'] = 'calculadora', ['damageItem'] = 'calculadora-queimada' },
	{ ['item'] = 'tablet', ['damageItem'] = 'tablet-queimado' },
	{ ['item'] = 'notebook', ['damageItem'] = 'notebook-queimado' },
	{ ['item'] = 'controleremoto', ['damageItem'] = 'controleremoto-queimado' },
	{ ['item'] = 'baterias', ['damageItem'] = 'baterias-queimadas' },
	{ ['item'] = 'radio', ['damageItem'] = 'radio-queimado' },
	
	{ ['item'] = 'passaporte', ['damageItem'] = nil },
	{ ['item'] = 'portearmas', ['damageItem'] = nil },
	{ ['item'] = 'identidade', ['damageItem'] = nil },
	{ ['item'] = 'cnh', ['damageItem'] = nil },
	{ ['item'] = 'repairkit', ['damageItem'] = nil },
	{ ['item'] = 'dinheiro', ['damageItem'] = nil },
	{ ['item'] = 'cartao-debito', ['damageItem'] = nil },
	{ ['item'] = 'maquininha', ['damageItem'] = 'maquininha-queimada' },

	{ ['item'] = 'drone-basic1', ['damageItem'] = nil },
	{ ['item'] = 'drone-basic2', ['damageItem'] = nil },
	{ ['item'] = 'drone-basic3', ['damageItem'] = nil },
	{ ['item'] = 'drone-advanced1', ['damageItem'] = nil },
	{ ['item'] = 'drone-advanced2', ['damageItem'] = nil },
	{ ['item'] = 'drone-advanced3', ['damageItem'] = nil },
	{ ['item'] = 'drone-police', ['damageItem'] = nil },
	{ ['item'] = 'carrinho', ['damageItem'] = nil },

	{ ['item'] = 'camisinha', ['damageItem'] = nil },
	{ ['item'] = 'vibrador', ['damageItem'] = nil },
	{ ['item'] = 'kit', ['damageItem'] = nil },
	
	{ ['item'] = 'dinheiro-sujo', ['damageItem'] = nil },
	{ ['item'] = 'algema', ['damageItem'] = nil },
	{ ['item'] = 'lockpick', ['damageItem'] = nil },
	{ ['item'] = 'capuz', ['damageItem'] = nil },
	{ ['item'] = 'placa', ['damageItem'] = nil },

	{ ['item'] = 'serra', ['damageItem'] = nil },
	{ ['item'] = 'furadeira', ['damageItem'] = nil },
	{ ['item'] = 'pa-jardinagem', ['damageItem'] = nil },

	{ ['item'] = 'garrafa-vazia', ['damageItem'] = nil },
	{ ['item'] = 'ponta-britadeira', ['damageItem'] = nil },

	{ ['item'] = 'minerio-diamante', ['damageItem'] = nil },
	{ ['item'] = 'minerio-ouro', ['damageItem'] = nil },
	{ ['item'] = 'minerio-prata', ['damageItem'] = nil },
	{ ['item'] = 'minerio-ferro', ['damageItem'] = nil },

	{ ['item'] = 'diamante', ['damageItem'] = nil },
	{ ['item'] = 'barra-ouro', ['damageItem'] = nil },
	{ ['item'] = 'barra-prata', ['damageItem'] = nil },
	{ ['item'] = 'barra-ferro', ['damageItem'] = nil },
	
	{ ['item'] = 'agua', ['damageItem'] = nil },
	{ ['item'] = 'leite', ['damageItem'] = nil },
	{ ['item'] = 'cafe', ['damageItem'] = nil },
	{ ['item'] = 'cafecleite', ['damageItem'] = nil },
	{ ['item'] = 'cafeexpresso', ['damageItem'] = nil },
	{ ['item'] = 'capuccino', ['damageItem'] = nil },
	{ ['item'] = 'frappuccino', ['damageItem'] = nil },
	{ ['item'] = 'cha', ['damageItem'] = nil },
	{ ['item'] = 'icecha', ['damageItem'] = nil },
	{ ['item'] = 'sprunk', ['damageItem'] = nil },
	{ ['item'] = 'cola', ['damageItem'] = nil },
	{ ['item'] = 'energetico', ['damageItem'] = nil },

	{ ['item'] = 'pibwassen', ['damageItem'] = nil },
	{ ['item'] = 'tequilya', ['damageItem'] = nil },
	{ ['item'] = 'patriot', ['damageItem'] = nil },
	{ ['item'] = 'blarneys', ['damageItem'] = nil },
	{ ['item'] = 'jakeys', ['damageItem'] = nil },
	{ ['item'] = 'barracho', ['damageItem'] = nil },
	{ ['item'] = 'ragga', ['damageItem'] = nil },
	{ ['item'] = 'nogo', ['damageItem'] = nil },
	{ ['item'] = 'mount', ['damageItem'] = nil },
	{ ['item'] = 'cherenkov', ['damageItem'] = nil },
	{ ['item'] = 'bourgeoix', ['damageItem'] = nil },
	{ ['item'] = 'bleuterd', ['damageItem'] = nil },

	{ ['item'] = 'sanduiche', ['damageItem'] = nil },
	{ ['item'] = 'rosquinha', ['damageItem'] = nil },
	{ ['item'] = 'hotdog', ['damageItem'] = nil },
	{ ['item'] = 'xburguer', ['damageItem'] = nil },
	{ ['item'] = 'chips', ['damageItem'] = nil },
	{ ['item'] = 'batataf', ['damageItem'] = nil },
	{ ['item'] = 'pizza', ['damageItem'] = nil },
	{ ['item'] = 'frango', ['damageItem'] = nil },
	{ ['item'] = 'bcereal', ['damageItem'] = nil },
	{ ['item'] = 'bchocolate', ['damageItem'] = nil },
	{ ['item'] = 'taco', ['damageItem'] = nil },

	{ ['item'] = 'paracetamil', ['damageItem'] = nil },
	{ ['item'] = 'voltarom', ['damageItem'] = nil },
	{ ['item'] = 'trandrylux', ['damageItem'] = nil },
	{ ['item'] = 'dorfrex', ['damageItem'] = nil },
	{ ['item'] = 'buscopom', ['damageItem'] = nil },

	{ ['item'] = 'r-paracetamil', ['damageItem'] = nil },
	{ ['item'] = 'r-voltarom', ['damageItem'] = nil },
	{ ['item'] = 'r-trandrylux', ['damageItem'] = nil },
	{ ['item'] = 'r-dorfrex', ['damageItem'] = nil },
	{ ['item'] = 'r-buscopom', ['damageItem'] = nil },

	{ ['item'] = 'metanfetamina', ['damageItem'] = nil },
	{ ['item'] = 'composito', ['damageItem'] = nil },

	{ ['item'] = 'nitrato-amonia', ['damageItem'] = nil },
	{ ['item'] = 'hidroxido-sodio', ['damageItem'] = nil },
	{ ['item'] = 'pseudoefedrina', ['damageItem'] = nil },
	{ ['item'] = 'eter', ['damageItem'] = nil },

	{ ['item'] = 'cocaina', ['damageItem'] = nil },
	{ ['item'] = 'pasta-base', ['damageItem'] = nil },

	{ ['item'] = 'acido-sulfurico', ['damageItem'] = nil },
	{ ['item'] = 'folhas-coca', ['damageItem'] = nil },
	{ ['item'] = 'calcio-po', ['damageItem'] = nil },
	{ ['item'] = 'querosene', ['damageItem'] = nil },

	{ ['item'] = 'marijuana', ['damageItem'] = nil },
	{ ['item'] = 'folha-marijuana', ['damageItem'] = nil },

	{ ['item'] = 'corpo-ak47', ['damageItem'] = nil },
	{ ['item'] = 'corpo-aks74u', ['damageItem'] = nil },
	{ ['item'] = 'corpo-uzi', ['damageItem'] = nil },
	{ ['item'] = 'corpo-glock', ['damageItem'] = nil },
	{ ['item'] = 'corpo-magnum', ['damageItem'] = nil },

	{ ['item'] = 'molas', ['damageItem'] = nil },
	{ ['item'] = 'placa-metal', ['damageItem'] = nil },
	{ ['item'] = 'gatilho', ['damageItem'] = nil },
	{ ['item'] = 'capsulas', ['damageItem'] = nil },
	{ ['item'] = 'polvora', ['damageItem'] = nil },

	{ ['item'] = 'garrafa-leite', ['damageItem'] = nil },

	{ ['item'] = 'isca', ['damageItem'] = nil },

	{ ['item'] = 'tora', ['damageItem'] = nil },

	{ ['item'] = 'saco-lixo', ['damageItem'] = nil },

	{ ['item'] = 'encomenda', ['damageItem'] = nil },
	{ ['item'] = 'caixa-vazia', ['damageItem'] = nil },

	{ ['item'] = 'malote', ['damageItem'] = nil },

	{ ['item'] = 'semente-marijuana', ['damageItem'] = nil },
	{ ['item'] = 'semente-blueberry', ['damageItem'] = nil },

	{ ['item'] = 'laranja', ['damageItem'] = nil },
	{ ['item'] = 'tomate', ['damageItem'] = nil },
	{ ['item'] = 'blueberry', ['damageItem'] = nil },

	{ ['item'] = 'transmissao', ['damageItem'] = nil },
	{ ['item'] = 'suspensao', ['damageItem'] = nil },
	{ ['item'] = 'portas', ['damageItem'] = nil },
	{ ['item'] = 'borrachas', ['damageItem'] = nil },
	{ ['item'] = 'pneus', ['damageItem'] = nil },
	{ ['item'] = 'capo', ['damageItem'] = nil },
	{ ['item'] = 'bateria-carro', ['damageItem'] = nil },
	{ ['item'] = 'motor', ['damageItem'] = nil },

	{ ['item'] = 'wbodyWEAPON_DAGGER', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_BAT', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_BOTTLE', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_CROWBAR', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_FLASHLIGHT', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_GOLFCLUB', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_HAMMER', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_WEAPON_HATCHET', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_WEAPON_KNUCKLES', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_KNIFE', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_MACHETE', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_SWITCHBLADE', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_NIGHTSTICK', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_WHENCH', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_BATTLEAXE', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_POOLCUE', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_STONE_HATCHET', ['damageItem'] = nil },

	{ ['item'] = 'wbodyWEAPON_PISTOL', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_PISTOL_MK2', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_COMBATPISTOL', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_APPISTOL', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_STUNGUN', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_PISTOL50', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_SNSPISTOL', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_SNSPISTOL_MK2', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_HEAVYPISTOL', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_VINTAGEPISTOL', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_FLAREGUN', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_MARKSMANPISTOL', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_REVOLVER', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_REVOLVER_MK2', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_DOUBLEACTION', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_RAYPISTOL', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_CERAMICPISTOL', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_NAVYREVOLVER', ['damageItem'] = nil },

	{ ['item'] = 'wammoWEAPON_PISTOL', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_PISTOL_MK2', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_COMBATPISTOL', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_APPISTOL', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_STUNGUN', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_PISTOL50', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_SNSPISTOL', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_SNSPISTOL_MK2', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_HEAVYPISTOL', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_VINTAGEPISTOL', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_FLAREGUN', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_MARKSMANPISTOL', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_REVOLVER', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_REVOLVER_MK2', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_DOUBLEACTION', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_RAYPISTOL', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_CERAMICPISTOL', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_NAVYREVOLVER', ['damageItem'] = nil },

	{ ['item'] = 'wbodyWEAPON_MICROSMG', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_SMG', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_SMG_MK2', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_ASSAULTSMG', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_COMBATPDW', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_MACHINEPISTOL', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_MINISMG', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_RAYCARBINE', ['damageItem'] = nil },

	{ ['item'] = 'wammoWEAPON_MICROSMG', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_SMG', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_SMG_MK2', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_ASSAULTSMG', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_COMBATPDW', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_MACHINEPISTOL', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_MINISMG', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_RAYCARBINE', ['damageItem'] = nil },

	{ ['item'] = 'wammoWEAPON_PUMPSHOTGUN', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_PUMPSHOTGUN_MK2', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_SAWNOFFSHOTGUN', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_ASSAULTSHOTGUN', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_BULLPUPSHOTGUN', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_MUSKET', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_HEAVYSHOTGUN', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_DBSHOTGUN', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_AUTOSHOTGUN', ['damageItem'] = nil },

	{ ['item'] = 'wammoWEAPON_PUMPSHOTGUN', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_PUMPSHOTGUN_MK2', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_SAWNOFFSHOTGUN', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_ASSAULTSHOTGUN', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_BULLPUPSHOTGUN', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_MUSKET', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_HEAVYSHOTGUN', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_DBSHOTGUN', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_AUTOSHOTGUN', ['damageItem'] = nil },

	{ ['item'] = 'wbodyWEAPON_ASSAULTRIFLE', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_ASSAULTRIFLE_MK2', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_CARBINERIFLE', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_CARBINERIFLE_MK2', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_ADVANCEDRIFLE', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_SPECIALCARBINE', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_SPECIALCARBINE_MK2', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_BULLPUPRIFLE', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_BULLPUPRIFLE_MK2', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_COMPACTRIFLE', ['damageItem'] = nil },

	{ ['item'] = 'wammoWEAPON_ASSAULTRIFLE', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_ASSAULTRIFLE_MK2', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_CARBINERIFLE', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_CARBINERIFLE_MK2', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_ADVANCEDRIFLE', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_SPECIALCARBINE', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_SPECIALCARBINE_MK2', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_BULLPUPRIFLE', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_BULLPUPRIFLE_MK2', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_COMPACTRIFLE', ['damageItem'] = nil },

	{ ['item'] = 'wbodyWEAPON_MG', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_COMBATMG', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_COMBATMG_MK2', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_GUSENBERG', ['damageItem'] = nil },

	{ ['item'] = 'wammoWEAPON_MG', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_COMBATMG', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_COMBATMG_MK2', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_GUSENBERG', ['damageItem'] = nil },

	{ ['item'] = 'wbodyWEAPON_SNIPERRIFLE', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_HEAVYSNIPER', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_HEAVYSNIPER_MK2', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_MASKMANRIFLE', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_MASKMANRIFLE_MK2', ['damageItem'] = nil },

	{ ['item'] = 'wammoWEAPON_SNIPERRIFLE', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_HEAVYSNIPER', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_HEAVYSNIPER_MK2', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_MASKMANRIFLE', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_MASKMANRIFLE_MK2', ['damageItem'] = nil },

	{ ['item'] = 'wbodyWEAPON_RPG', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_GRENADELAUNCHER', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_GRENADELAUNCHER_SMOKE', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_MINIGUN', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_FIREWORK', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_RAILGUN', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_HOMINGLAUNCHER', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_COMPACTLAUNCHER', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_RAYMINIGUN', ['damageItem'] = nil },

	{ ['item'] = 'wammoWEAPON_RPG', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_GRENADELAUNCHER', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_GRENADELAUNCHER_SMOKE', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_MINIGUN', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_FIREWORK', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_RAILGUN', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_HOMINGLAUNCHER', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_COMPACTLAUNCHER', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_RAYMINIGUN', ['damageItem'] = nil },

	{ ['item'] = 'wbodyWEAPON_GRANADE', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_BZGAS', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_MOLOTOV', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_STICKYBOMB', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_PROXMINE', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_SNOWBALL', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_PIPEBOMB', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_BALL', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_SMOKEGRENADE', ['damageItem'] = nil },
	{ ['item'] = 'wbodyWEAPON_FLARE', ['damageItem'] = nil },

	{ ['item'] = 'wammoWEAPON_PETROLCAN', ['damageItem'] = nil },
	{ ['item'] = 'wammoGADGET_PARACHUTE', ['damageItem'] = nil },
	{ ['item'] = 'wammoWEAPON_FIREEXTINGUISHER', ['damageItem'] = nil }
}