config = {}

config.permissions = 'off-manager'

config.hairfades = {
    [1] = { label = 'Degradê 01', dlc = 'mphipster_overlays', texture = 'FM_Hip_F_Hair_000_a' },
    [2] = { label = 'Degradê 02', dlc = 'mphipster_overlays', texture = 'FM_Hip_F_Hair_000_b' },
    [3] = { label = 'Degradê 03', dlc = 'mphipster_overlays', texture = 'FM_Hip_F_Hair_000_c' },
    [4] = { label = 'Degradê 04', dlc = 'mphipster_overlays', texture = 'FM_Hip_F_Hair_000_d' },
    [5] = { label = 'Degradê 05', dlc = 'mphipster_overlays', texture = 'FM_Hip_F_Hair_000_e' },
    [6] = { label = 'Degradê 06', dlc = 'mphipster_overlays', texture = 'FM_F_Hair_017_a' },
    [7] = { label = 'Degradê 07', dlc = 'mphipster_overlays', texture = 'FM_F_Hair_017_b' },
    [8] = { label = 'Degradê 08', dlc = 'mphipster_overlays', texture = 'FM_F_Hair_017_c' },
    [9] = { label = 'Degradê 09', dlc = 'mphipster_overlays', texture = 'FM_F_Hair_017_d' },
    [10] = { label = 'Degradê 10', dlc = 'mphipster_overlays', texture = 'FM_F_Hair_017_e' },
    [11] = { label = 'Degradê 11', dlc = 'mphipster_overlays', texture = 'FM_F_Hair_020_a' },
    [12] = { label = 'Degradê 12', dlc = 'mphipster_overlays', texture = 'FM_F_Hair_020_b' },
    [13] = { label = 'Degradê 13', dlc = 'mphipster_overlays', texture = 'FM_F_Hair_020_c' },
    [14] = { label = 'Degradê 14', dlc = 'mphipster_overlays', texture = 'FM_F_Hair_020_d' },
    [15] = { label = 'Degradê 15', dlc = 'mphipster_overlays', texture = 'FM_F_Hair_020_e' },
    [16] = { label = 'Degradê 16', dlc = 'mphipster_overlays', texture = 'FM_Hip_M_Hair_000_a'},
    [17] = { label = 'Degradê 17', dlc = 'mphipster_overlays', texture = 'FM_Hip_M_Hair_000_b'},
    [18] = { label = 'Degradê 18', dlc = 'mphipster_overlays', texture = 'FM_Hip_M_Hair_000_c'},
    [19] = { label = 'Degradê 19', dlc = 'mphipster_overlays', texture = 'FM_Hip_M_Hair_000_d'},
    [20] = { label = 'Degradê 20', dlc = 'mphipster_overlays', texture = 'FM_Hip_M_Hair_000_e'},
    [21] = { label = 'Degradê 21', dlc = 'mphipster_overlays', texture = 'FM_Hip_M_Hair_001_a'},
    [22] = { label = 'Degradê 22', dlc = 'mphipster_overlays', texture = 'FM_Hip_M_Hair_001_b'},
    [23] = { label = 'Degradê 23', dlc = 'mphipster_overlays', texture = 'FM_Hip_M_Hair_001_c'},
    [24] = { label = 'Degradê 24', dlc = 'mphipster_overlays', texture = 'FM_Hip_M_Hair_001_d'},
    [25] = { label = 'Degradê 25', dlc = 'mphipster_overlays', texture = 'FM_Hip_M_Hair_001_e'},
    [26] = { label = 'Degradê 26', dlc = 'mphipster_overlays', texture = 'FM_Disc_M_Hair_001_a'},
    [27] = { label = 'Degradê 27', dlc = 'mphipster_overlays', texture = 'FM_Disc_M_Hair_001_b'},
    [28] = { label = 'Degradê 28', dlc = 'mphipster_overlays', texture = 'FM_Disc_M_Hair_001_c'},
    [29] = { label = 'Degradê 29', dlc = 'mphipster_overlays', texture = 'FM_Disc_M_Hair_001_d'},
    [30] = { label = 'Degradê 30', dlc = 'mphipster_overlays', texture = 'FM_Disc_M_Hair_001_e'},
    [31] = { label = 'Degradê 31', dlc = 'mplowrider_overlays', texture = 'LR_F_Hair_000' },
    [32] = { label = 'Degradê 32', dlc = 'mplowrider_overlays', texture = 'LR_F_Hair_001' },
    [33] = { label = 'Degradê 33', dlc = 'mplowrider_overlays', texture = 'LR_F_Hair_002' },
    [34] = { label = 'Degradê 34', dlc = 'mplowrider2_overlays', texture = 'LR_F_Hair_003' },
    [35] = { label = 'Degradê 35', dlc = 'mplowrider2_overlays', texture = 'LR_F_Hair_004' },
    [36] = { label = 'Degradê 36', dlc = 'mplowrider2_overlays', texture = 'LR_F_Hair_006' },
    [37] = { label = 'Degradê 37', dlc = 'mplowrider_overlays', texture = 'LR_M_Hair_000'},
    [38] = { label = 'Degradê 38', dlc = 'mplowrider_overlays', texture = 'LR_M_Hair_001'},
    [39] = { label = 'Degradê 39', dlc = 'mplowrider_overlays', texture = 'LR_M_Hair_002'},
    [40] = { label = 'Degradê 40', dlc = 'mplowrider_overlays', texture = 'LR_M_Hair_003'},
    [41] = { label = 'Degradê 41', dlc = 'mplowrider2_overlays', texture = 'LR_M_Hair_004'},
    [42] = { label = 'Degradê 42', dlc = 'mplowrider2_overlays', texture = 'LR_M_Hair_005'},
    [43] = { label = 'Degradê 43', dlc = 'mplowrider2_overlays', texture = 'LR_M_Hair_006'},
    [44] = { label = 'Degradê 44', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_003_a' },
    [45] = { label = 'Degradê 45', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_003_b' },
    [46] = { label = 'Degradê 46', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_003_c' },
    [47] = { label = 'Degradê 47', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_003_d' },
    [48] = { label = 'Degradê 48', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_003_e' },
    [49] = { label = 'Degradê 49', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_005_a' },
    [50] = { label = 'Degradê 50', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_005_b' },
    [51] = { label = 'Degradê 51', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_005_c' },
    [52] = { label = 'Degradê 52', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_005_d' },
    [53] = { label = 'Degradê 53', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_005_e' },
    [54] = { label = 'Degradê 54', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_006_a' },
    [55] = { label = 'Degradê 55', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_006_b' },
    [56] = { label = 'Degradê 56', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_006_c' },
    [57] = { label = 'Degradê 57', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_006_d' },
    [58] = { label = 'Degradê 58', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_006_e' },
    [59] = { label = 'Degradê 59', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_013_a' },
    [60] = { label = 'Degradê 60', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_013_b' },
    [61] = { label = 'Degradê 61', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_013_c' },
    [62] = { label = 'Degradê 62', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_013_d' },
    [63] = { label = 'Degradê 63', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_013_e' },
    [64] = { label = 'Degradê 64', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_014_a' },
    [65] = { label = 'Degradê 65', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_014_b' },
    [66] = { label = 'Degradê 66', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_014_c' },
    [67] = { label = 'Degradê 67', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_014_d' },
    [68] = { label = 'Degradê 68', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_014_e' },
    [69] = { label = 'Degradê 69', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_long_a' },
    [70] = { label = 'Degradê 70', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_long_b' },
    [71] = { label = 'Degradê 71', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_long_c' },
    [72] = { label = 'Degradê 72', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_long_d' },
    [73] = { label = 'Degradê 73', dlc = 'multiplayer_overlays', texture = 'FM_F_Hair_long_e' },
    [74] = { label = 'Degradê 74', dlc = 'multiplayer_overlays', texture = 'NG_F_Hair_001' },
    [75] = { label = 'Degradê 75', dlc = 'multiplayer_overlays', texture = 'NG_F_Hair_002' },
    [76] = { label = 'Degradê 76', dlc = 'multiplayer_overlays', texture = 'NG_F_Hair_003' },
    [77] = { label = 'Degradê 77', dlc = 'multiplayer_overlays', texture = 'NG_F_Hair_004' },
    [78] = { label = 'Degradê 78', dlc = 'multiplayer_overlays', texture = 'NG_F_Hair_005' },
    [79] = { label = 'Degradê 79', dlc = 'multiplayer_overlays', texture = 'NG_F_Hair_006' },
    [80] = { label = 'Degradê 80', dlc = 'multiplayer_overlays', texture = 'NG_F_Hair_007' },
    [81] = { label = 'Degradê 81', dlc = 'multiplayer_overlays', texture = 'NG_F_Hair_008' },
    [82] = { label = 'Degradê 82', dlc = 'multiplayer_overlays', texture = 'NG_F_Hair_009' },
    [83] = { label = 'Degradê 83', dlc = 'multiplayer_overlays', texture = 'NG_F_Hair_010' },
    [84] = { label = 'Degradê 84', dlc = 'multiplayer_overlays', texture = 'NG_F_Hair_011' },
    [85] = { label = 'Degradê 85', dlc = 'multiplayer_overlays', texture = 'NG_F_Hair_012' },
    [86] = { label = 'Degradê 86', dlc = 'multiplayer_overlays', texture = 'NG_F_Hair_013' },
    [87] = { label = 'Degradê 87', dlc = 'multiplayer_overlays', texture = 'NG_F_Hair_014' },
    [88] = { label = 'Degradê 88', dlc = 'multiplayer_overlays', texture = 'NG_F_Hair_015' },
    [89] = { label = 'Degradê 89', dlc = 'multiplayer_overlays', texture = 'NGBea_F_Hair_000' },
    [90] = { label = 'Degradê 90', dlc = 'multiplayer_overlays', texture = 'NGBea_F_Hair_001' },
    [91] = { label = 'Degradê 91', dlc = 'multiplayer_overlays', texture = 'NGBus_F_Hair_000' },
    [92] = { label = 'Degradê 92', dlc = 'multiplayer_overlays', texture = 'NGBus_F_Hair_001' },
    [93] = { label = 'Degradê 93', dlc = 'multiplayer_overlays', texture = 'NGHip_F_Hair_000' },
    [94] = { label = 'Degradê 94', dlc = 'multiplayer_overlays', texture = 'NGHip_F_Hair_001' },
    [95] = { label = 'Degradê 95', dlc = 'multiplayer_overlays', texture = 'NGInd_F_Hair_000' },
    [96] = { label = 'Degradê 96', dlc = 'multiplayer_overlays', texture = 'NG_M_Hair_001' },
    [97] = { label = 'Degradê 97', dlc = 'multiplayer_overlays', texture = 'NG_M_Hair_002' },
    [98] = { label = 'Degradê 98', dlc = 'multiplayer_overlays', texture = 'NG_M_Hair_003' },
    [99] = { label = 'Degradê 99', dlc = 'multiplayer_overlays', texture = 'NG_M_Hair_004' },
    [100] = { label = 'Degradê 100', dlc = 'multiplayer_overlays', texture = 'NG_M_Hair_005' },
    [101] = { label = 'Degradê 101', dlc = 'multiplayer_overlays', texture = 'NG_M_Hair_006' },
    [102] = { label = 'Degradê 102', dlc = 'multiplayer_overlays', texture = 'NG_M_Hair_007' },
    [103] = { label = 'Degradê 103', dlc = 'multiplayer_overlays', texture = 'NG_M_Hair_008' },
    [104] = { label = 'Degradê 104', dlc = 'multiplayer_overlays', texture = 'NG_M_Hair_009' },
    [105] = { label = 'Degradê 105', dlc = 'multiplayer_overlays', texture = 'NG_M_Hair_010' },
    [106] = { label = 'Degradê 106', dlc = 'multiplayer_overlays', texture = 'NG_M_Hair_011' },
    [107] = { label = 'Degradê 107', dlc = 'multiplayer_overlays', texture = 'NG_M_Hair_012' },
    [108] = { label = 'Degradê 108', dlc = 'multiplayer_overlays', texture = 'NG_M_Hair_013' },
    [109] = { label = 'Degradê 109', dlc = 'multiplayer_overlays', texture = 'NG_M_Hair_014' },
    [110] = { label = 'Degradê 110', dlc = 'multiplayer_overlays', texture = 'NG_M_Hair_015' },
    [111] = { label = 'Degradê 111', dlc = 'multiplayer_overlays', texture = 'NGBea_M_Hair_000' },
    [112] = { label = 'Degradê 112', dlc = 'multiplayer_overlays', texture = 'NGBea_M_Hair_001' },
    [113] = { label = 'Degradê 113', dlc = 'multiplayer_overlays', texture = 'NGBus_M_Hair_000' },
    [114] = { label = 'Degradê 114', dlc = 'multiplayer_overlays', texture = 'NGBus_M_Hair_001' },
    [115] = { label = 'Degradê 115', dlc = 'multiplayer_overlays', texture = 'NGHip_M_Hair_000' },
    [116] = { label = 'Degradê 116', dlc = 'multiplayer_overlays', texture = 'NGHip_M_Hair_001' },
    [117] = { label = 'Degradê 117', dlc = 'multiplayer_overlays', texture = 'NGInd_M_Hair_000' },
    [118] = { label = 'Degradê 118', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_001_a'},
    [119] = { label = 'Degradê 119', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_001_b'},
    [120] = { label = 'Degradê 120', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_001_c'},
    [121] = { label = 'Degradê 121', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_001_d'},
    [122] = { label = 'Degradê 122', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_001_e'},
    [123] = { label = 'Degradê 123', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_003_a'},
    [124] = { label = 'Degradê 124', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_003_b'},
    [125] = { label = 'Degradê 125', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_003_c'},
    [126] = { label = 'Degradê 126', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_003_d'},
    [127] = { label = 'Degradê 127', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_003_e'},
    [128] = { label = 'Degradê 128', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_006_a'},
    [129] = { label = 'Degradê 129', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_006_b'},
    [130] = { label = 'Degradê 130', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_006_c'},
    [131] = { label = 'Degradê 131', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_006_d'},
    [132] = { label = 'Degradê 132', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_006_e'},
    [133] = { label = 'Degradê 133', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_008_a'},
    [134] = { label = 'Degradê 134', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_008_b'},
    [135] = { label = 'Degradê 135', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_008_c'},
    [136] = { label = 'Degradê 136', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_008_d'},
    [137] = { label = 'Degradê 137', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_008_e'},
    [138] = { label = 'Degradê 138', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_long_a'},
    [139] = { label = 'Degradê 139', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_long_b'},
    [140] = { label = 'Degradê 140', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_long_c'},
    [141] = { label = 'Degradê 141', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_long_d'},
    [142] = { label = 'Degradê 142', dlc = 'multiplayer_overlays', texture = 'FM_M_Hair_long_e'},
    [143] = { label = 'Degradê 143', dlc = 'mpgunrunning_overlays', texture = 'MP_Gunrunning_Hair_F_000_F'},
    [144] = { label = 'Degradê 144', dlc = 'mpgunrunning_overlays', texture = 'MP_Gunrunning_Hair_F_001_F'},
    [145] = { label = 'Degradê 145', dlc = 'mpgunrunning_overlays', texture = 'MP_Gunrunning_Hair_M_000_M'},
    [146] = { label = 'Degradê 146', dlc = 'mpgunrunning_overlays', texture = 'MP_Gunrunning_Hair_M_001_M'},
    [147] = { label ='Degradê 147', dlc = 'mpbiker_overlays', texture = 'MP_Biker_Hair_000_F' },
    [148] = { label ='Degradê 148', dlc = 'mpbiker_overlays', texture = 'MP_Biker_Hair_001_F' },
    [149] = { label ='Degradê 149', dlc = 'mpbiker_overlays', texture = 'MP_Biker_Hair_002_F' },
    [150] = { label ='Degradê 150', dlc = 'mpbiker_overlays', texture = 'MP_Biker_Hair_003_F' },
    [151] = { label ='Degradê 151', dlc = 'mpbiker_overlays', texture = 'MP_Biker_Hair_004_F' },
    [152] = { label ='Degradê 152', dlc = 'mpbiker_overlays', texture = 'MP_Biker_Hair_005_F' },
    [153] = { label ='Degradê 153', dlc = 'mpbiker_overlays', texture = 'MP_Biker_Hair_006_F' },   
    [154] = { label ='Degradê 154', dlc = 'mpbiker_overlays', texture = 'MP_Biker_Hair_000_M' },
    [155] = { label ='Degradê 155', dlc = 'mpbiker_overlays', texture = 'MP_Biker_Hair_001_M' },
    [156] = { label ='Degradê 156', dlc = 'mpbiker_overlays', texture = 'MP_Biker_Hair_002_M' },
    [157] = { label ='Degradê 157', dlc = 'mpbiker_overlays', texture = 'MP_Biker_Hair_003_M' },
    [158] = { label ='Degradê 158', dlc = 'mpbiker_overlays', texture = 'MP_Biker_Hair_004_M' },
    [159] = { label ='Degradê 159', dlc = 'mpbiker_overlays', texture = 'MP_Biker_Hair_005_M' },
    [160] = { label ='Degradê 160', dlc = 'mpbiker_overlays', texture = 'MP_Biker_Hair_006_M' },
    [161] = { label ='Degradê 161', dlc = 'mpxmas_604490_overlays', texture = 'Hair_014_Fix' }, 
    [162] = { label = 'Degradê 162', dlc = 'mpbusiness_overlays', texture = 'FM_Bus_F_Hair_a'},
    [163] = { label = 'Degradê 163', dlc = 'mpbusiness_overlays', texture = 'FM_Bus_F_Hair_b'},
    [164] = { label = 'Degradê 164', dlc = 'mpbusiness_overlays', texture = 'FM_Bus_F_Hair_c'},
    [165] = { label = 'Degradê 165', dlc = 'mpbusiness_overlays', texture = 'FM_Bus_F_Hair_d'},
    [166] = { label = 'Degradê 166', dlc = 'mpbusiness_overlays', texture = 'FM_Bus_F_Hair_e'},
    [167] = { label = 'Degradê 167', dlc = 'mpbusiness_overlays', texture = 'FM_Bus_M_Hair_000_a'},
    [168] = { label = 'Degradê 168', dlc = 'mpbusiness_overlays', texture = 'FM_Bus_M_Hair_000_b'},
    [169] = { label = 'Degradê 169', dlc = 'mpbusiness_overlays', texture = 'FM_Bus_M_Hair_000_c'},
    [170] = { label = 'Degradê 170', dlc = 'mpbusiness_overlays', texture = 'FM_Bus_M_Hair_000_d'},
    [171] = { label = 'Degradê 171', dlc = 'mpbusiness_overlays', texture = 'FM_Bus_M_Hair_000_e'},
    [172] = { label = 'Degradê 172', dlc = 'mpbusiness_overlays', texture = 'FM_Bus_M_Hair_001_a'},
    [173] = { label = 'Degradê 173', dlc = 'mpbusiness_overlays', texture = 'FM_Bus_M_Hair_001_b'},
    [174] = { label = 'Degradê 174', dlc = 'mpbusiness_overlays', texture = 'FM_Bus_M_Hair_001_c'},
    [175] = { label = 'Degradê 175', dlc = 'mpbusiness_overlays', texture = 'FM_Bus_M_Hair_001_d'},
    [176] = { label = 'Degradê 176', dlc = 'mpbusiness_overlays', texture = 'FM_Bus_M_Hair_001_e'},
    [177] = { label = 'Degradê 177', dlc = 'mpbeach_overlays', texture = 'FM_Hair_Fuzz' }
}